# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
        - python: 3.5

before_install:
    - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq maarten-fonville/protobuf/protobuf
before_script:
    - cd test
script:
    - py.test
