# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
        - python: 3.5

before_install:
    - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
    - sudo apt-get update -qq
    # We have to install protoc, and python libs for both python and python3, since mypy runs py3
    - sudo apt-get install -qq protobuf-compiler python-protobuf python3-protobuf python3 python3-pip python3-setuptools
    # We have to install from git to get the latest typeshed, which includes some
    # important stubs for google.protobuf
    - python3 -m pip install -U git+git://github.com/python/mypy.git
script:
    - ./run_test.sh
